
function(info_pre_collector target_name output_path)
    message(STATUS "target_name: ${target_name}")
    file(APPEND ${output_path}/info.txt "target_name: ${target_name}\n")
    if(TARGET ${target_name})
        get_target_property(target_sources ${target_name} SOURCES)
        get_target_property(target_include_dirs ${target_name} INCLUDE_DIRECTORIES)
        get_target_property(target_link_libs ${target_name} INTERFACE_LINK_LIBRARIES)
        get_target_property(target_compile_options ${target_name} COMPILE_OPTIONS)
        get_target_property(target_compile_defs ${target_name} COMPILE_DEFINITIONS)
        get_target_property(target_link_options ${target_name} LINK_OPTIONS)

        message(STATUS "target_sources: ${target_sources}")
        message(STATUS "target_include_dirs: ${target_include_dirs}")
        message(STATUS "target_link_libs: ${target_link_libs}")
        message(STATUS "target_compile_options: ${target_compile_options}")
        message(STATUS "target_compile_defs: ${target_compile_defs}")
        message(STATUS "target_link_options: ${target_link_options}")

        file(APPEND ${output_path}/info.txt "target_name: ${target_name}\n")
        file(APPEND ${output_path}/info.txt "target_sources: ${target_sources}\n")
        file(APPEND ${output_path}/info.txt "target_include_dirs: ${target_include_dirs}\n")
        file(APPEND ${output_path}/info.txt "target_link_libs: ${target_link_libs}\n")
        file(APPEND ${output_path}/info.txt "target_compile_options: ${target_compile_options}\n")
        file(APPEND ${output_path}/info.txt "target_compile_defs: ${target_compile_defs}\n")
        file(APPEND ${output_path}/info.txt "target_link_options: ${target_link_options}\n")
        file(APPEND ${output_path}/info.txt "\n")

        if(target_link_libs)
            foreach(lib IN LISTS target_link_libs)
                message(STATUS "Processing linked library: ${lib}")
                file(APPEND ${output_path}/info.txt "Processing linked library: ${lib}\n")
                if(TARGET ${lib})
                        message(STATUS "Target found succesfully: ${lib}")
                        file(APPEND ${output_path}/info.txt "Target found succesfully: ${lib}\n")
                        info_pre_collector(${lib} ${output_path})
                endif()
            endforeach()
        endif()
    endif()

endfunction()

message(STATUS "TARGET_NAME: ${TARGET_NAME} OUTPUT_PATH: ${OUTPUT_PATH}")
if(TARGET_NAME AND OUTPUT_PATH)
    message(STATUS "TARGET_NAME: ${TARGET_NAME} OUTPUT_PATH: ${OUTPUT_PATH}")
    file(APPEND ${OUTPUT_PATH}/info.txt "TARGET_NAME: ${TARGET_NAME} OUTPUT_PATH: ${OUTPUT_PATH}")
    info_pre_collector(${TARGET_NAME} ${OUTPUT_PATH})
else()
    # file(APPEND ${OUTPUT_PATH}/info.txt "TARGET_NAME: ${TARGET_NAME} OUTPUT_PATH: ${OUTPUT_PATH}")
    message(STATUS "TARGET_NAME: ${TARGET_NAME} OUTPUT_PATH: ${OUTPUT_PATH}")
endif()
