include(color_print)
include(code_refactor)

macro(diagnostic)
  get_filename_component(libname ${CMAKE_CURRENT_SOURCE_DIR} NAME)
  if(NOT TARGET ${libname})
    set(libname ${ARGN})
  else()
    if(code_format)
      clang_format(${libname})
    endif()
  endif()

  if(CMAKE_DEBUG_MSG)
    color_print(cyan "--> ${libname}: ")
    get_target_property(list ${libname} INCLUDE_DIRECTORIES)
    message(STATUS "${libname} target INCLUDE_DIRECTORIES list: -> ${list}")
    scan_header_dirs(${libname} scaned_files)  
    message(STATUS "${libname} target INCLUDE_FILES list: -> ${scaned_files}")
    get_target_property(list ${libname} SOURCE_DIR)
    message(STATUS "${libname} target SOURCE_DIR list: -> ${list}")
    get_target_property(list ${libname} SOURCES)
    message(STATUS "${libname} target SOURCES list: -> ${list}")
    get_target_property(list ${libname} INTERFACE_SOURCES)
    message(STATUS "${libname} target INTERFACE_SOURCES list: -> ${list}")
    get_target_property(list ${libname} COMPILE_DEFINITIONS )
    message(STATUS "${libname} target COMPILE_DEFINITIONS list: -> ${list}")
    get_target_property(list ${libname} LINK_LIBRARIES)
    message(STATUS "${libname} target LINK_LIBRARIES list: -> ${list}")
    get_target_property(list ${libname} COMPILE_OPTIONS)
    message(STATUS "${libname} target COMPILE_OPTIONS list: -> ${list}")
    get_target_property(list ${libname} C_STANDARD)
    message(STATUS "${libname} target C_STANDARD list: -> ${list}")
    # Extract the BUILD_INTERFACE path from the INCLUDE_DIRECTORIES property
    get_target_property(RAW_INCLUDE_DIRS ${libname} INCLUDE_DIRECTORIES)
    string(REGEX REPLACE ".*$<BUILD_INTERFACE:([^>]*)>.*" "\\1" BUILD_INTERFACE_PATH ${RAW_INCLUDE_DIRS})

    # Convert the BUILD_INTERFACE path to an absolute path
    get_filename_component(ABSOLUTE_PATH ${RAW_INCLUDE_DIRS} ABSOLUTE)

    message(STATUS "Absolute Build Interface Path: ${ABSOLUTE_PATH}")
  else()
    color_print(cyan "--> ${libname}: ")
  endif()
endmacro()

